### ISSUE TITLE
problems with latest search from command line

### ISSUE THREAD

**Issue by poorboy44** [DrSkippy/Gnip-Python-Search-API-Utilities#15]
I updated to the latest search, but the command line functionality seems to not be working for me now. Something with the init?

[tw-172-17-97-153 Gnip-Python-Search-API-Utilities (master)]$ ./search_api.py -f"from:gnip" json
Traceback (most recent call last):
  File "./search_api.py", line 133, in <module>
    print GnipSearchCMD()()
  File "./search_api.py", line 68, in __init__
    , self.token_list_size
TypeError: __init__() takes at most 6 arguments (7 given)

**Comment by DrSkippy** [comment]
Sorry, looks like a dependency in the setup.py file needs to be updated.  I think this might be solved by installing the latest gnacs:

    pip install gnacs --upgrade
