### ISSUE TITLE
problems using Search utilities to write stdout to file

### ISSUE THREAD

**Issue by poorboy44** [DrSkippy/Gnip-Python-Search-API-Utilities#16]
[tw-172-17-97-153 Gnip-Python-Search-API-Utilities (master)]$ search_api.py -f"from:dove" json > dove.json
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "/Users/snelson/Python/PyPy-2.2.1/bin/search_api.py", line 133, in <module>
    print GnipSearchCMD()()
  File "/Users/snelson/Python/PyPy-2.2.1/lib-python/2.7/codecs.py", line 352, in write
    self.stream.write(data)
IOError: [Errno 9] Bad file descriptor: '<fdopen>'

**Comment by DrSkippy** [comment]
The preferred method for output is to use the option:

  -w OUTPUT_FILE_PATH, --output-file-path OUTPUT_FILE_PATH
                        Create files in ./OUTPUT-FILE-PATH. This path must
                        exists and will not be created. This options is
                        available only with -a option. Default is no output
                        files.
