### ISSUE TITLE
Pip install GAPI install issues

### ISSUE THREAD

**Issue by poorboy44** [DrSkippy/Gnip-Python-Search-API-Utilities#17]
Some kind of UJSON error:

[tw-172-17-97-153 dove_body_image]$ sudo pip install gapi --upgrade
Password:
Requirement already up-to-date: gapi in /Users/snelson/Python/PyPy-2.2.1/site-packages
Requirement already up-to-date: gnacs>=1.0.0 in /Users/snelson/Python/PyPy-2.2.1/site-packages (from gapi)
Requirement already up-to-date: sngrams>=0.1.5 in /Users/snelson/Python/PyPy-2.2.1/site-packages (from gapi)
Requirement already up-to-date: requests>2.2.0 in /Users/snelson/Python/PyPy-2.2.1/site-packages (from gapi)
Downloading/unpacking ujson>=1.2 (from gnacs>=1.0.0->gapi)
  Downloading ujson-1.33.zip (197kB): 197kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/ujson/setup.py) egg_info for package ujson
    
Installing collected packages: ujson
  Running setup.py install for ujson
    building 'ujson' extension
    cc -arch x86_64 -O2 -fPIC -Wimplicit -I./python -I./lib -I/Users/snelson/Python/PyPy-2.2.1/include -c ./python/ujson.c -o build/temp.macosx-10.10-x86_64-2.7/./python/ujson.o -D_GNU_SOURCE
    cc -arch x86_64 -O2 -fPIC -Wimplicit -I./python -I./lib -I/Users/snelson/Python/PyPy-2.2.1/include -c ./python/objToJSON.c -o build/temp.macosx-10.10-x86_64-2.7/./python/objToJSON.o -D_GNU_SOURCE
    ./python/objToJSON.c:523:13: warning: implicit declaration of function 'PyObject_Malloc' is invalid in C99 [-Wimplicit-function-declaration]
      tc->prv = PyObject_Malloc(sizeof(TypeContext));
                ^
    ./python/objToJSON.c:523:11: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
      tc->prv = PyObject_Malloc(sizeof(TypeContext));
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ./python/objToJSON.c:663:17: warning: implicit declaration of function 'PyAnySet_Check' is invalid in C99 [-Wimplicit-function-declaration]
                                                                                                    if (PyAnySet_Check(obj))
                                                                                                        ^
    ./python/objToJSON.c:722:13: warning: implicit declaration of function 'PyObject_Free' is invalid in C99 [-Wimplicit-function-declaration]
                                                                                                    PyObject_Free(tc->prv);
                                                                                                    ^
    ./python/objToJSON.c:818:3: error: use of undeclared identifier 'PyObject_Realloc'; did you mean 'PyObject_dealloc'?
                    PyObject_Realloc,
                    ^~~~~~~~~~~~~~~~
                    PyObject_dealloc
    /Users/snelson/Python/PyPy-2.2.1/include/pypy_decl.h:327:18: note: 'PyObject_dealloc' declared here
    PyAPI_FUNC(void) PyObject_dealloc(PyObject *arg0);
                     ^
    ./python/objToJSON.c:817:3: warning: incompatible pointer types initializing 'JSPFN_MALLOC' (aka 'void *(*)(size_t)') with an expression of type 'int ()' [-Wincompatible-pointer-types]
                    PyObject_Malloc,
                    ^~~~~~~~~~~~~~~
    ./python/objToJSON.c:818:3: warning: incompatible pointer types initializing 'JSPFN_REALLOC' (aka 'void *(*)(void *, size_t)') with an expression of type 'void (PyObject *)' [-Wincompatible-pointer-types]
                    PyObject_Realloc,
                    ^~~~~~~~~~~~~~~~
    ./python/objToJSON.c:819:3: warning: incompatible pointer types initializing 'JSPFN_FREE' (aka 'void (*)(void *)') with an expression of type 'int ()' [-Wincompatible-pointer-types]
                    PyObject_Free,
                    ^~~~~~~~~~~~~
    7 warnings and 1 error generated.
    error: command 'cc' failed with exit status 1
    Complete output from command /Users/snelson/Python/PyPy-2.2.1/bin/pypy -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/ujson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t0z0Mm-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

building 'ujson' extension

creating build

creating build/temp.macosx-10.10-x86_64-2.7

creating build/temp.macosx-10.10-x86_64-2.7/python

creating build/temp.macosx-10.10-x86_64-2.7/lib

cc -arch x86_64 -O2 -fPIC -Wimplicit -I./python -I./lib -I/Users/snelson/Python/PyPy-2.2.1/include -c ./python/ujson.c -o build/temp.macosx-10.10-x86_64-2.7/./python/ujson.o -D_GNU_SOURCE

cc -arch x86_64 -O2 -fPIC -Wimplicit -I./python -I./lib -I/Users/snelson/Python/PyPy-2.2.1/include -c ./python/objToJSON.c -o build/temp.macosx-10.10-x86_64-2.7/./python/objToJSON.o -D_GNU_SOURCE

./python/objToJSON.c:523:13: warning: implicit declaration of function 'PyObject_Malloc' is invalid in C99 [-Wimplicit-function-declaration]

  tc->prv = PyObject_Malloc(sizeof(TypeContext));

            ^

./python/objToJSON.c:523:11: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]

  tc->prv = PyObject_Malloc(sizeof(TypeContext));

          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

./python/objToJSON.c:663:17: warning: implicit declaration of function 'PyAnySet_Check' is invalid in C99 [-Wimplicit-function-declaration]

                                                                                                if (PyAnySet_Check(obj))

                                                                                                    ^

./python/objToJSON.c:722:13: warning: implicit declaration of function 'PyObject_Free' is invalid in C99 [-Wimplicit-function-declaration]

                                                                                                PyObject_Free(tc->prv);

                                                                                                ^

./python/objToJSON.c:818:3: error: use of undeclared identifier 'PyObject_Realloc'; did you mean 'PyObject_dealloc'?

                PyObject_Realloc,

                ^~~~~~~~~~~~~~~~

                PyObject_dealloc

/Users/snelson/Python/PyPy-2.2.1/include/pypy_decl.h:327:18: note: 'PyObject_dealloc' declared here

PyAPI_FUNC(void) PyObject_dealloc(PyObject *arg0);

                 ^

./python/objToJSON.c:817:3: warning: incompatible pointer types initializing 'JSPFN_MALLOC' (aka 'void *(*)(size_t)') with an expression of type 'int ()' [-Wincompatible-pointer-types]

                PyObject_Malloc,

                ^~~~~~~~~~~~~~~

./python/objToJSON.c:818:3: warning: incompatible pointer types initializing 'JSPFN_REALLOC' (aka 'void *(*)(void *, size_t)') with an expression of type 'void (PyObject *)' [-Wincompatible-pointer-types]

                PyObject_Realloc,

                ^~~~~~~~~~~~~~~~

./python/objToJSON.c:819:3: warning: incompatible pointer types initializing 'JSPFN_FREE' (aka 'void (*)(void *)') with an expression of type 'int ()' [-Wincompatible-pointer-types]

                PyObject_Free,

                ^~~~~~~~~~~~~

7 warnings and 1 error generated.

error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/snelson/Python/PyPy-2.2.1/bin/pypy -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/ujson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t0z0Mm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/ujson
Storing debug log for failure in /Users/snelson/.pip/pip.log

**Comment by DrSkippy** [comment]
ujson is an optimization that is not strictly required for running the application. Unfortunately, it depends on having a compiler installed.  I think the script will still run with the default json compiler included in the standard library.
