### ISSUE TITLE
silent error

### ISSUE THREAD

**Issue by blehman** [DrSkippy/Gnip-Python-Search-API-Utilities#24]
When an incorrect url is set in the .gnip creds, the following script produces a silent error:

./gnip_search.py -t -s'2011-03-01T00:00' -f'#d3js' -e'2015-11-21T00:00' json

**Comment by DrSkippy** [comment]
You should now see something like this when you use a v1 endpoint for a v2 query:

$ ./gnip_search.py -t -s'2011-03-01T00:00' -f'#d3js' -e'2015-11-21T00:00' json
WARNING: You set the search v2 flag, but your URL appears to point to a v1 endpoint.
Exiting with HTTP error code 422
ERROR Message: Could not accept your search request: Invalid date for query parameter 'fromDate'. Can't request historical activities prior to 2013/01/01/01/01
