### ISSUE TITLE
gnip_time_series.py fails silently with "Search V1"

### ISSUE THREAD

**Issue by jrmontag** [DrSkippy/Gnip-Python-Search-API-Utilities#25]
If the .gnip configuration file does not include a Full-Archive (Search V2) endpoint, running the ``gnip_time_series.py`` tool fails silently. 

If you think to look in the log, you find an message that gets you started in the right direction (below), but a more helpful error message (to stderr or stdout) would help get the user pointed in the right direction.

```bash
INFO:root:################# started 2016-01-08 13:32:03.762697 #################
DEBUG:root:CHAR_UPPER_CUTOFF=20,TWEET_SAMPLE=4000,MIN_SNR=2.0,MAX_N_PEAKS=7,MAX_PEAK_WIDTH=20,MIN_PEAK_WIDTH=1,SEARCH_PEAK_WIDTH=3,N_MOVING=4,OUTLIER_FRAC=0.8,PLOTS_PREFIX=./plots,PLOT_DELTA_Y=1.2
INFO:root:attempting to read config file ./.gnip
ERROR:root:gnipSearch timeline tools require Search V2. Exiting.
```

**Comment by DrSkippy** [comment]
Added terminal message to the same effect.
